# Generated by ariadne-codegen on 2023-09-14 06:23
# Source: src/ripple_energy/graphql_queries

from typing import Optional

from .base_model import BaseModel
from .enums import CoopCoopStatusChoices


class GetActiveCoopStatus(BaseModel):
    coop: Optional["GetActiveCoopStatusCoop"]


class GetActiveCoopStatusCoop(BaseModel):
    id: str
    status: CoopCoopStatusChoices


GetActiveCoopStatus.update_forward_refs()
GetActiveCoopStatusCoop.update_forward_refs()
