# Generated by ariadne-codegen on 2023-09-13 00:38
# Source: src/ripple_energy/graphql

from typing import Optional

from .base_model import BaseModel
from .fragments import MemberFragment


class GetMember(BaseModel):
    member: Optional["GetMemberMember"]


class GetMemberMember(MemberFragment):
    pass


GetMember.update_forward_refs()
GetMemberMember.update_forward_refs()
