# Generated by ariadne-codegen on 2023-09-14 06:23
# Source: src/ripple_energy/graphql_queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class TokenAuth(BaseModel):
    token_auth: "TokenAuthTokenAuth" = Field(alias="tokenAuth")


class TokenAuthTokenAuth(BaseModel):
    token: Optional[str]


TokenAuth.update_forward_refs()
TokenAuthTokenAuth.update_forward_refs()
