# Generated by ariadne-codegen on 2023-09-09 13:53
# Source: src/ripple_energy/graphql

from pydantic import Field

from .base_model import BaseModel


class TokenAuth(BaseModel):
    token_auth: "TokenAuthTokenAuth" = Field(alias="tokenAuth")


TokenAuth.update_forward_refs()
