# Generated by ariadne-codegen on 2023-09-14 06:23
# Source: src/ripple_energy/graphql_queries

from typing import Optional

from .base_model import BaseModel


class Version(BaseModel):
    version: Optional[str]


Version.update_forward_refs()
